// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa79g8CoNClXk8rWMkpz2pBT3g-nsZWCM',
    appId: '1:185395246606:web:11b16dd63241739c766e5f',
    messagingSenderId: '185395246606',
    projectId: 'todo-app-37f3c',
    authDomain: 'todo-app-37f3c.firebaseapp.com',
    storageBucket: 'todo-app-37f3c.appspot.com',
    measurementId: 'G-JVYQ8LQMQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2tEpHxo3abF9bkk2C7oEu1kHRutEFe5s',
    appId: '1:185395246606:android:c2c77281b74f64b1766e5f',
    messagingSenderId: '185395246606',
    projectId: 'todo-app-37f3c',
    storageBucket: 'todo-app-37f3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1CGaNy1gH6aWwXGmFh_v3ngpzuC_4PfI',
    appId: '1:185395246606:ios:1fa602ab462854c3766e5f',
    messagingSenderId: '185395246606',
    projectId: 'todo-app-37f3c',
    storageBucket: 'todo-app-37f3c.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1CGaNy1gH6aWwXGmFh_v3ngpzuC_4PfI',
    appId: '1:185395246606:ios:1fa602ab462854c3766e5f',
    messagingSenderId: '185395246606',
    projectId: 'todo-app-37f3c',
    storageBucket: 'todo-app-37f3c.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa79g8CoNClXk8rWMkpz2pBT3g-nsZWCM',
    appId: '1:185395246606:web:38700a265e0da898766e5f',
    messagingSenderId: '185395246606',
    projectId: 'todo-app-37f3c',
    authDomain: 'todo-app-37f3c.firebaseapp.com',
    storageBucket: 'todo-app-37f3c.appspot.com',
    measurementId: 'G-PX8022FZCZ',
  );
}
